/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.utilities;

import java.util.LinkedList;

public class StringUtils {
  public static String join(LinkedList<String> source) {
    return JoinUtils.join(source);
  }

  public static LinkedList<String> split(String source) {
    return SplitUtils.split(source);
  }
}
